<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <Authors>IFYates</Authors>
		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <Version>2.2.0</Version>
        <PackageProjectUrl>https://github.com/IFYates/Shimr</PackageProjectUrl>
        <RepositoryUrl>https://github.com/IFYates/Shimr</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>
        <PackageReleaseNotes>[v2.2.0] Support shimming multiple interfaces at once
[v2.1.4] Static shims support implemented interface members
[v2.1.3] Improved handling of hidden members
[v2.1.2] More deterministic handling of conflicting methods
[v2.1.1] Improved performance of task shimming</PackageReleaseNotes>
        <Copyright>(c) IFYates</Copyright>
        <Description>Utility for creating a dynamic object facade/proxy to allow for using an object as an interface that it does not explicitly implement.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <DocumentationFile>IFY.Shimr.xml</DocumentationFile>
    </PropertyGroup>
    
    <ItemGroup>
      <None Remove="IFY.Shimr.xml" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\README.md">
        <Pack>true</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    </ItemGroup>
</Project>