<Project Sdk="Microsoft.NET.Sdk">
	
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <Authors>IFYates</Authors>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/IFYates/Shimr</PackageProjectUrl>
        <RepositoryUrl>https://github.com/IFYates/Shimr</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>
        <Copyright>(c) IFYates</Copyright>
        <Description>Utility for creating a dynamic object facade/proxy to allow for using an object as an interface that it does not explicitly implement.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <DocumentationFile>IFY.Shimr.xml</DocumentationFile>
	
        <_ReleaseNotesFirstLine>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/../RELEASE_NOTES.txt').Substring(1, $([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)/../RELEASE_NOTES.txt').IndexOf('
'))))</_ReleaseNotesFirstLine>
        <Version>$(_ReleaseNotesFirstLine.Trim())</Version>

	</PropertyGroup>
    
    <ItemGroup>
      <None Remove="IFY.Shimr.xml" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\README.md">
        <Pack>true</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    </ItemGroup>

	<Target Name="PreparePackageReleaseNotesFromFile" BeforeTargets="GenerateNuspec">
		<ReadLinesFromFile File="../RELEASE_NOTES.txt">
			<Output TaskParameter="Lines" ItemName="ReleaseNoteLines" />
		</ReadLinesFromFile>
		<PropertyGroup>
			<PackageReleaseNotes>@(ReleaseNoteLines, '%0a')</PackageReleaseNotes>
		</PropertyGroup>
	</Target>
	
</Project>