name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - uses: actions/checkout@v2

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Restore tools
      run: dotnet tool restore
      
    - name: Set branch-based environment variables
      uses: iamtheyammer/branch-env-vars@v1.1.2
      with:
        BUILD_CONFIG: |
          master:Release
          !default:Debug

    # Build
    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore

    - name: Publish package
      uses: nanoufo/action-upload-artifacts-and-release-assets@v1.4
      with:
        path: ./**/IFY.Shimr.*.*nupkg

    # Test & coverage
    - name: Test and coverage
      run: dotnet coverlet ./IFY.Shimr.Tests/bin/$BUILD_CONFIG/net6.0/IFY.Shimr.Tests.dll --target "dotnet" --targetargs "test ./IFY.Shimr.Tests/IFY.Shimr.Tests.csproj --configuration $BUILD_CONFIG --no-build" --include-test-assembly --format lcov -o cover.lcov
    - name: Report coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cover.lcov

    # Mutation test
    - name: Configure Stryker.NET for IFY.Phorm
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: stryker-config.json
        write-mode: overwrite
        contents: |
          {
            "stryker-config": {
              "project": "IFY.Shimr.csproj",
              "test-projects": ["./IFY.Shimr.Tests/IFY.Shimr.Tests.csproj"],
              "project-info": {
                "name": "github.com/IFYates/IFY.Shimr",
                "module": "IFY.Shimr",
                "version": "${{ github.base_ref }}"
              },
              "reporters": ["cleartext", "html", "dashboard"]
            }
          }
    - name: Run Stryker.NET
      run: dotnet stryker --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD }}
    - name: Upload mutation report
      uses: actions/upload-artifact@v4
      with:
        name: mutation-report.html
        path: ./**/mutation-report.html
