name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: Coverlet coverage test
#      uses: b3b00/coverlet-action@1.1.1
#      with:
#        output: ../lcov.info
#        outputFormat: lcov
#        testProject: Shimterface.Tests/Shimterface.Standard.Tests.csproj
    - name: stryker dotnet
      uses: naveen497/actions@0.0.1
