name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: Coverlet coverage test
#      uses: b3b00/coverlet-action@1.1.1
#      with:
#        output: ../lcov.info
#        outputFormat: lcov
#        testProject: Shimterface.Tests/Shimterface.Standard.Tests.csproj
##       run: coverlet /path/to/test-assembly.dll --target "dotnet" --targetargs "test /path/to/test-project --no-build"
#    - name: stryker dotnet
#      uses: naveen497/actions@0.0.1

    - name: Install Stryker.NET (1/2)
      run: dotnet tool install -g dotnet-stryker
    - name: Install Stryker.NET (2/2)
      run: dotnet tool restore
    - name: Run Stryker.NET
      run: cd ./Shimterface.Tests/; dotnet stryker
    - name: Upload mutation report
      uses: actions/upload-artifact@v2.2.2
      with:
        name: mutation-report.html
        path: ./**/mutation-report.html
      
